### ISSUE TITLE
automatic_signing should default to False not True

### ISSUE THREAD

**Issue by kirit93** [FactomProject/factom-harmony-connect-python-sdk#10]
In the constructor for `FactomClient`, I believe that `automatic_signing` should be set to `False`. Under the current implementation, a chain cannot be created unless it is signed. 

`factom_client.chains.create(content = "Test", external_ids = ['Test', 'One', 'Two'])`
results in `Exception: signer_private_key is required.`

Changing `automatic_signing` to `False` would allow unsigned chains to be created using the simple syntax above and would require passing an identity chain and private key to the function call if the chain needs to be signed.

The same thing applies to creating entries as well.

I'd also like to hear opinions on making content default to some text so that it is not a mandatory field while creating a chain.

```
def create(content: str = "", external_ids: list = [], **options):
    """ """
    signer_chain_id         = options.get('signer_chain_id', None)
    signer_private_key      = options.get('signer_private_key', None)
    callback_url            = options.get('callback_url', None)
    callback_stages         = options.get('callback_stages', [])
    sign                    = self.automatic_signing
    ids_base64              = []

    if signer_chain_id and signer_private_key:
        if KeyCommon.validate_checksum(signer_private_key):
            sign            = True
        else:
            raise Exception("Invalid Private Key passed")

    if sign and (signer_chain_id == None or signer_private_key == None):
        raise("The Chain can't be signed unless BOTH signer identity chain and signer private key are passed..")

    if not hasattr(external_ids, '__iter__'):
        raise Exception("External IDs must be iterable")

    if not hasattr(callback_stages, '__iter__'):
        raise Exception("Callback Stages must be iterable")

    if callback_url and not validators.url(callback_url):
        raise Exception("callback_url is an invalid url format.")

    if len(external_ids) < 1:
        raise Exception("Not enough External IDs provided")

    # Should content be a mandatory field? It seems to me that as long as External IDs are passed, a default first entry can be made. 
    if content == "":
        content             = "This is the first entry in the chain with External IDs: " + ", ".join(str(_id) for _id in external_ids)
    
    if sign:
        time_stamp          = datetime.datetime.utcnow().isoformat()
        message             = signer_chain_id + content + time_stamp
        signature           = KeyCommon.sign_content(signer_private_key, message)
        signer_public_key   = KeyCommon.get_public_key_from_private_key(signer_private_key)
        items               =\
        [
            encode_string("SignedChain"),
            encode_string(bytes([0x01])),
            encode_string(signer_chain_id),
            encode_string(signer_public_key),
            signature,
            encode_string(time_stamp)
        ]
        ids_base64          = items + [encode_string(val) for val in external_ids]

    data                    = \
    {
        "external_ids"  : ids_base64,
        "content"       : encode_string(content)
    }

    if callback_url:
        data["callback_url"]        = callback_url
    if callback_stages:
        data["callback_stages"]     = callback_stages

    return self.request_handler.post(factom_sdk.utils.consts.CHAINS_URL, data)
```

**Comment by Cahl-Dee** [comment]
# Topic 1: autosigning
This was a subject of much debate. We determined that it is unsafe to write data to the blockchain unsigned and therefore the default behavior should be to automatically sign the entries and chains. 

Not signing data that you write to the blockchain opens you up to impersonation, replay attacks, and other malicious activity. For this reason, we highly suggest against it. Meanwhile, there may be some use cases that we have not thought of where it is appropriate, so a user can simply instantiate their instance of the SDK with auto-signing off. 

I do want to fill you in on two roadmap items we would like to add to the SDKs, but do not have the resources to do in the near term (the SDK is open source and we would be happy for community members to contribute):
1. Much like Stripe does with their SDKs ([see authenticate example here](https://stripe.com/docs/api/authentication?lang=node)), while the configuration is set during instantiation, we will update all methods to allow for overrides to be passed for each configuration parameter.
2. We are aware that some advanced customers may use alternative methods to sign their entries and chains. For this reason, the signature verification enumeration is [true/false/custom function] when reading chains and entries. In the spirit of such, we also hope to allow users to pass in their own functions for custom chain and entry signing methodologies.

# Topic 2: Required Content Field
The data being secured within the blockchain should go within the Content field. By doing so, it enables the content that is being secured to have it's own location and be uniquely accessible for generating a digital signature. 

As such, writing an entry or chain with only external IDs will provide no value as there is no data being secured via the digital signatures. 

---
I understand these may not be the answers you were hoping to hear, but for 99% of Harmony users, these "guiderails" are important for helping them rapidly implement blockchain within their applications. 

I believe we have designed these SDKs in a way that supports these users while also leaving the flexibility for all foreseeable (and countless unforeseeable) use cases. If you can share concrete use cases that we have unintentially prevented we would be more than happy to reconsider. I do want to provide a disclaimer that we are extremely resource constrained at this time working on future projects and will need to prioritize any changes accordingly.

**Comment by Cahl-Dee** [comment]
### Topic 1 (UPDATE)
Based on offline discussions, @kirit93 provided a very strong use case for wanting `automatic_signing` to occasionally be _false_.

An undocumented concept at the Harmony level is the fact that on the Factom Blockchain, chain_id's can be precomputed (see [docs](https://github.com/FactomProject/FactomDocs/blob/194ea18a8b0705e549459575347690f53f258e54/factomDataStructureDetails.md#chainid) and note that a **Chain Name** is the set of `external_ids` used when creating it).

In certain scenarios, where multiple entities need to write data to the same chain, but not have any off-chain communication, it is important that they are able to precompute the same `chain_id` to write to. In order to do so, creating an unsigned chain is necessary to avoid the inclusion of the unpredictable `external_ids` that are added when signing (such as the timestamp and signer's identity chain_id - see #11 ).

As such, we will implement the ability to override the `automatic_signing` instantiation parameter on a per method call. For example, a user can instantiate an instance of the SDK with `automatic_signing` set to _true_ (the default), yet call the [create chain method](https://github.com/FactomProject/factom-harmony-connect-python-sdk/blob/master/documentation/chains.md#chains_create) with an override of `automatic_signing` set to _false_ for a given execution. 

@kirit93 has been so kind as to implementing this and creating a PR #14 that addresses his needs.

This issue will be closed, as @kirit93 's needs have been addressed and the planned go-forward parts of this issue (implementing the "per method override" functionality globally across the SDK) will be broken out into a new one.
